### ISSUE TITLE
List prize winners in readme for hacktoberfest 2020 edition

### ISSUE THREAD

**Issue by musps** [paypal/hacktoberfest#5]
Hello,

It's been one month since hacktoberfest ended and I was wondering
who are the winners of the socks and who is the big selected person of the backpack?

Maybe you can update the readme and list all Github names?

I participated in different repositories and I was just wondering who are the first 20 + 1 random picked ^^

Thank you!

**Comment by musps** [comment]
@mstuart @shrutikapoor08 @mnicpt 
Do you have an idea?

**Comment by mstuart** [comment]
Hi @musps, thanks for following up. We updated the README and announced the contributors there. We'll collect up addresses shortly and send PayPal socks out. Thanks!
