### ISSUE TITLE
Collecting up addresses

### ISSUE THREAD

**Issue by mstuart** [paypal/hacktoberfest#6]
Hi everyone (listed below)! Thanks for contributing to Hacktoberfest! If you're interested in some PayPal socks, can you please reply w/ your Twitter or e-mail or some way of contacting you? That way, I can reach out to you to collect your shipping address. Thanks!

@ReazerDev (collected address)
@M-krishna (collected address)
@BhautikChudasama (sent e-mail)
@musps (collected address)
@TheTripleV (sent e-mail)
@Abdul-Sen (sent e-mail)
@ANovokmet (collected address)
@gruiz90 (collected address)
@pushpinder107 (sent e-mail)
@anthonykhoa (collected address)
@Cijin (sent e-mail)
@PaulieScanlon
@jchoi136 (sent e-mail)
@daniel-shuy (sent e-mail)
@logesr (collected address)
@hndoss
@SlyBouhafs (sent e-mail)
@Lsmoura (collected address)

![img](https://camo.githubusercontent.com/113075ab19def790a9b57415fdcbf3d595985302cbe2c9509a4ad542c3a2b713/68747470733a2f2f7777772e74686570617970616c73686f702e636f6d2f476574496d6167652e617368783f506174683d25376525326641737365747325326650726f64756374496d61676573253266505030302d303333372d47726f75702e6a7067266d61696e7461696e417370656374526174696f3d74727565266d61784865696768743d363030266d617857696474683d363030)

**Comment by lsmoura** [comment]
Hello!

Email address for @lsmoura: sergio@moura.ca

Kudos!

Kind regards,
- Sergio Moura

**Comment by logesr** [comment]
Hi Mark,

You can reach me in this email : loges.r@thoughtworks.com

**Comment by M-krishna** [comment]
Hey @mstuart , you can reach me through krishnamurugan589@gmail.com

**Comment by mstuart** [comment]
Added @Cijin ^^

**Comment by mstuart** [comment]
Thanks @lsmoura , @logesr , @M-krishna. Just sent you an e-mail, if you wanted to delete your e-mail address here. :)

**Comment by musps** [comment]
Hi,
you can contact me via twitter dm:
https://twitter.com/e34Maby88

**Comment by gruiz90** [comment]
Hi @mstuart , you can reach me in this email:
germanruizravi@gmail.com

**Comment by SlyBouhafs** [comment]
Hi @mstuart, you can reach me here: khmedj@gmail.com

**Comment by TheTripleV** [comment]
@mstuart, my email address is vovveti2@illinois.edu
Thanks!

**Comment by daniel-shuy** [comment]
Thanks @mstuart! My email address is daniel_shuy@hotmail.com

**Comment by pushpinder107** [comment]
Hi Mark,

You can contact me at pushpinder@me.com

**Comment by ANovokmet** [comment]
Hello @mstuart 

My contact is ante.je.zakon@gmail.com.

Thank you,
@ANovokmet

**Comment by anthonykhoa** [comment]
Hi Mark!

My email is anthonykhoatran@gmail.com

Thanks so much!

- Anthony

**Comment by jchoi136** [comment]
Hi Mark,

My email is jchoi136@gmail.com

Thanks!
Jiwoo

**Comment by BhautikChudasama** [comment]
Namaste Mark,

Here is my email address hello@bhautik.me and Twitter account is bhautiktweets.

Thanks,
Bhautik )

**Comment by Cijin** [comment]
Heya,

Email: cijininurhood@gmail.com

**Comment by Abdul-Sen** [comment]
Haha hope im not too late, you can reach me at abdul.rm.jahangir@gmail.com
________________________________

**Comment by shrutikapoor08** [comment]
Closing this issue. Congratulations to all the 2020 winners 🎉

**Comment by musps** [comment]
@mstuart, @shrutikapoor08 Thx but,
Still haven't heard about any packages!
I don't know if all packages have been sent yet or not but since it's almost 1 year later,
can I ask for updates ?

Sorry to bother you about that here!

**Comment by mstuart** [comment]
Hi @musps! They should have been sent out already. A few other contributors from last year have received theirs (even internationally), but we had some issues w/ the swag distributor last year w/ COVID. I know they're fulfilling orders now though.

Any other 2020 contributors that haven't received theirs, please reply here and I'll re-submit the orders. Apologies!

**Comment by lsmoura** [comment]
I thought I was the only one! 😅 

No packages here either.

**Comment by lsmoura** [comment]
@mstuart if you’re going to send it again, I’ll be moving in November. Any chance I can update my address?

**Comment by mstuart** [comment]
@lsmoura Yikes! Reply to our e-mail thread w/ your new address once you've moved and I'll send it out

**Comment by daniel-shuy** [comment]
Haven't got it either, thanks!

**Comment by logesr** [comment]
I haven't received the package yet. Thanks.

**Comment by BhautikChudasama** [comment]
Same here, I haven't received yet.

**Comment by M-krishna** [comment]
> Hi @musps! They should have been sent out already. A few other contributors from last year have received theirs (even internationally), but we had some issues w/ the swag distributor last year w/ COVID. I know they're fulfilling orders now though.
> 
> Any other 2020 contributors that haven't received theirs, please reply here and I'll re-submit the orders. Apologies!

Same, I didn't receive the package yet.

**Comment by jchoi136** [comment]
I haven't received it yet too. Thanks!

**Comment by pushpinder107** [comment]
Same, haven't received it yet!

**Comment by SlyBouhafs** [comment]
Hi! I Haven't received any package.

**Comment by mstuart** [comment]
Thanks everyone! I'll reach out to you separately to confirm your addresses and will create new orders w/ the swag vendor. Have a great weekend!

**Comment by mstuart** [comment]
Hi @BhautikChudasama, I don't have your shipping address. I reached out to you over e-mail, but for some reason, it bounced. I can't DM you on Twitter either. I just followed you. Can you follow me back and DM me?
